[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' yarn build"  # Your main build command with increased memory

[build.environment]
  PYTHON_VERSION = "3.12.0"  # Using Python 3.12
  NODE_VERSION = "20"        # Use compatible version from package.json

  # Skip requirements.txt installation
  NETLIFY_USE_YARN = "true"
  NETLIFY_RESTORE_PYTHON = "false"  # Prevent automatic Python setup
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
